apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: loack-demo-secret
spec:
  name: loack-demo-secret
  description: loack demo secret
  secretString:
    namespace: default
    name: my-app-creds
    key: password
