apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: s3.services.k8s.aws
      kind: Bucket
    patch: |
      - op: add
        path: /spec/encryption
        value:
          rules:
            - applyServerSideEncryptionByDefault:
                sseAlgorithm: AES256
              bucketKeyEnabled: false
